---
title: "CS-4200 Final Project"
author: "Ryan McMurray"
format:
  revealjs:
    theme: moon
    slide-number: true
    width: 1600
    height: 900
    embed-resources: true
execute:
  echo: false
  warning: false
  message: false
  cache: false
---

# Setup
This product uses the NASS API but is not endorsed or certified by NASS.

## Load API

```{r}
#| label: libraries
library(rnassqs)
library(DBI)
library(RSQLite)
library(knitr)
library(kableExtra)
```

```{r}
#| label: setup
#| include: false
#| cache: true

nassqs_auth(key = "F69DFA8F-B2BA-3DBD-883E-C62A00818A29")
params <- list(commodity_desc = "MILK", year__GE = 2020)
raw_data <- nassqs(params)
```

```{r}
#| label: setup_db
#| include: false

raw_data$Value <- as.numeric(gsub(",", "", raw_data$Value))

con <- dbConnect(SQLite(), ":memory:")
dbWriteTable(con, "milk_data", raw_data)
```

```{sql}
--| label: sql_filtering
--| connection: con
--| output.var: "filtered_milk"
--| echo: true

SELECT state_alpha, year, unit_desc, Value 
FROM milk_data 
WHERE unit_desc = 'LB'
ORDER BY Value DESC
LIMIT 5;
```

```{r}
#| label: display_results
#| echo: false

knitr::kable(filtered_milk) |>
  kable_styling(full_width = FALSE, font_size = 24)
```

# Data Cleaning

```{r}
#| label: clean

```